---
- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Install http
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - httpd
    - php
    - php-fpm
    - php-mbstring
    - php-IDNA_Convert
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml
    - php-mysql

- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

#- name: disable SELinux
#  systemd:
#    name: setenforce
#    state: false
#    persistent: no

- name: Copy nginx configuration for wordpress
  template: src=default_nginx.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Copy httpd configuration for wordpress
  template: src=default_httpd.conf dest=/etc/httpd/conf.d/main.conf
  notify: restart httpd

- name: Copy main httpd configuration for wordpress
  template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify: restart httpd

- name: nginx service state
  service:
    name: nginx
    state: started
    enabled: yes

- name: httpd service state
  service:
    name: httpd
    state: started
    enabled: yes
